name: "Sync pre-commit identify tags"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  sync:
    if: github.repository == 'j178/prek'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
        with:
          version: "latest"
          enable-cache: true
      - name: "Sync identify tags"
        run: uv run --upgrade gen.py
        working-directory: ./crates/prek-identify

      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: "Sync latest identify tags"
          add-paths: |
            crates/prek-identify/src/tags.rs
          branch: "sync-identify-tags"
          title: "Sync latest identify tags"
          body: "Automated update for identify tags."
          base: "master"
          draft: true
